poligonos: PoligonoTest.o Poligono.o
	g++ PoligonoTest.o Poligono.o -o poligonos

PoligonoTest.o: PoligonoTest.cpp
	g++ -c PoligonoTest.cpp

Poligono.o: Poligono.cpp
	g++ -c Poligono.cpp

clean:
	rm *.o poligonos